# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_type', models.CharField(max_length=30)),
                ('cut_detail_type', models.CharField(max_length=30)),
                ('cut_quality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(max_length=30)),
                ('pass_detail_type', models.CharField(max_length=30)),
                ('pass_quality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_position', models.CharField(choices=[('1', 'Point Guard'), ('2', 'Shooting Guard'), ('3', 'Small Forward'), ('4', 'Power Forward'), ('5', 'Center')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Cut')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Game')),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Pass')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_type', models.CharField(max_length=30)),
                ('screen_detail_type', models.CharField(max_length=30)),
                ('screen_quality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_type', models.CharField(max_length=30)),
                ('shot_detail_type', models.CharField(max_length=30)),
                ('shot_quality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_city', models.CharField(max_length=30)),
                ('team_nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='possession',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Screen'),
        ),
        migrations.AddField(
            model_name='possession',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Shot'),
        ),
        migrations.AddField(
            model_name='possession',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Team'),
        ),
    ]
