# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20171214_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
